language: ruby
rvm:
  - 2.3.0
services: postgres
before_script:
  - rm config/database.yml
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database books_test;' -U postgres
  - bundle exec rake db:migrate
